//! Build script to auto-discover agent roles from prompts directory.
//!
//! This scans the `prompts/` directory at compile time and generates:
//! - A list of spawnable agent roles (excluding orchestrator and planner which are special)
//! - The prompt content for each role
//!
//! To add a new agent type, just create `prompts/newrole.txt` and rebuild.

use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let prompts_dir = Path::new("prompts");

    // Tell cargo to rerun if prompts directory changes
    println!("cargo:rerun-if-changed=prompts");

    // Collect all .txt files in prompts/
    let mut roles: Vec<(String, String)> = Vec::new(); // (role_name, prompt_path)

    if let Ok(entries) = fs::read_dir(prompts_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "txt") {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    let role_name = stem.to_lowercase();

                    // Skip orchestrator and planner - they're special system agents
                    if role_name == "orchestrator" || role_name == "planner" {
                        continue;
                    }

                    roles.push((role_name, path.display().to_string()));
                }
            }
        }
    }

    // Sort for deterministic output
    roles.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate the roles module
    let mut generated = String::new();

    generated.push_str("// Auto-generated agent roles from prompts directory.\n");
    generated.push_str("// DO NOT EDIT - regenerated by build.rs\n\n");

    // Generate the list of spawnable role names
    generated.push_str("/// Spawnable agent role names (auto-discovered from prompts/).\n");
    generated.push_str("pub const SPAWNABLE_ROLES: &[&str] = &[\n");
    for (role_name, _) in &roles {
        let _ = writeln!(generated, "    \"{role_name}\",");
    }
    generated.push_str("];\n\n");

    // Generate prompt content includes
    generated.push_str("/// Get prompt content for a role.\n");
    generated.push_str("pub fn get_prompt(role: &str) -> Option<&'static str> {\n");
    generated.push_str("    match role {\n");
    for (role_name, prompt_path) in &roles {
        // Use include_str! with the relative path
        let _ = writeln!(
            generated,
            "        \"{role_name}\" => Some(include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{prompt_path}\"))),",
        );
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n");

    // Write generated code
    let dest_path = Path::new(&out_dir).join("generated_roles.rs");
    fs::write(&dest_path, generated).unwrap();
}
